version: '3.9'
services:
  web:
    build: .
    command: python /django-facebook-with-docker/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-facebook-with-docker
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_datas:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_datas: