# Generated by Django 4.1.4 on 2023-01-12 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(upload_to='posts/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post_video', models.FileField(blank=True, upload_to='', validators=[post.validators.validate_file_extension])),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
