# Generated by Django 4.1.4 on 2023-01-09 08:54

from django.db import migrations, models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='post_video',
            field=models.FileField(blank=True, upload_to='', validators=[post.validators.validate_file_extension]),
        ),
    ]
