# Generated by Django 4.1.4 on 2023-01-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('special_status', 'Can edit other profiles')]},
        ),
    ]
