# Generated by Django 4.1.4 on 2023-01-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('special_status_other', 'Can edit other profiles'), ('special_status_edit', 'Can edit own profiles')]},
        ),
    ]
