# Generated by Django 4.1.4 on 2023-01-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='following',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='post',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
